### ISSUE TITLE
Linear referencing along the Borehole : how

### ISSUE THREAD

**Issue by sgrellet** [opengeospatial/boreholeie#23]
A quick issue to remember considering ISO 19148 for Borehole IE
ISO 19148:2012 - Geographic information -- Linear referencing

Note  : HY_Feature SWG did that exercise already and ended up using another (simpler) mechanism.
Both approaches should be considered

**Comment by daoane** [comment]
ISO19148 is already mentioned in the background/summary text on the vocab page.

**Comment by denevers** [comment]
Can anyone comment on suitability of Linear Referencing for borehole ?  I gave it a shot for GWML and gave up either it was too complicated or I did not understand it

**Comment by daoane** [comment]
It probably always depends on what your requirements are. To my understanding, the ICDP system is a linear reference system that is focussed on the sample material from a borehole, i.e. it describes the location of drill core and drill core observations in relationship to the borehole. I assume that other specialisations are possible.
1. Borehole from start point to total depth. These two points make up a linear reference system. In reality, this is the 3D borehole path, which in some projects is surveyed and in others is not. The start point is known for all boreholes. But even if the exact track of the borehole is not known, it's always measured length along the track from the start point, i.e. a valid reference system.
1. Core runs with a top depth and a length, i.e. the top of each core run is referenced along the borehole, the reference is the borehole start point.
1. Core sections: the reference is the core run, top section measured from the top of the core run; and of course section length.
1. Section unit: top and bottom measured from the top of the section. Same system for samples and lithological (or other) description.
1. Point on drill core (e.g. small sample or point/interpolated measurement on drill core) is measured from the top of the section (similar to section unit, but point and not from/to).


As a result, you have several nested linear reference systems. If the depth of a core run has to be corrected for some reasons, all sections, section units, points will follow along. Same for sections, all section units and points follow along. Depth along the borehole trajectory can be calculated and updated easily for all elements. With a borehole geometry survey, all measurements can be transformed to a suitable 3D SRS.
Is linear referencing suitable for boreholes? I would say yes of course, as long as you keep to the borehole and don't try to describe features that are off the linear reference. So it could be advantageous to have and maintain a linear reference system for the drill core while a 3D model is more appropriate for the interpretation and visualisation of the scientific results.
I think oriented drill core and oriented downhole logging (logging is along the linear reference of the borehole) show you the borders between linear referencing. In these cases, linear referencing is good for data acquisition but not for data integration and interpretation.
I can't tell how all this relates to ISO19148, which unfortunately is not among the standards available through our library or external access.

**Comment by dblodgett-usgs** [comment]
Commenting re: HY_Features with a bit of editorial.

We didn't use 19148 in full because the semantics don't align with typical hydrography usage. We did provide pretty explicit relationships between the HY_Features terminology for linear referencing and 19148 and they do basically align but the rigor of their alignment wasn't stressed as it didn't seem critical to the purpose of HY_Features.

I think the same logic applies to boreholes. While you are literally doing linear referencing, you are not using the same semantics or use cases that the linear-referencing ISO spec is design to satisfy. Forcing the semantics of that generalizations on your community that uses different words for basically the same concepts is totally unnecessary for something as rudimentary as measuring how far something is from a reference location.

As usual, @denevers is wise beyond his own recognition. 
> gave up either it was too complicated or I did not understand it 

This is basically why it makes no sense to use common standard semantics for something  so basic, IMHO.

**Comment by sgrellet** [comment]
This is basically what we ended up doing in the IE (BhML model inspired by ISO 19148)
Link with #22
